Update ci-theme.css
lonnieezell/ci-website pull request #91
Opened 2021-06-19 20:32 UTC by demyr17

Turned 2 vertical boxes into horizontal view. When we first prepared there were 3 versions of CI there : 4 - 3 and 2.. But then, only with 2 vertical boxes the page look was not meaningful without the third box.

2021-06-21 14:22 UTC, MGatner commented
Before:
<img width="1378" alt="before" src="https://user-images.githubusercontent.com/17572847/122777968-8b4f3880-d27a-11eb-8609-0642ca16621c.png">

After:
<img width="1377" alt="after" src="https://user-images.githubusercontent.com/17572847/122777977-8db19280-d27a-11eb-96aa-c7d1851d0a3e.png">

2021-06-21 14:26 UTC, MGatner requested changes
Looks better! Thanks for this. No need to leave comments on the old versions of things as that will all be available in the revision history. I made suggestions to remove these - if you click the "Files" tab you can use the "Add suggestion to batch" buttons to add all of them to a new commit and GitHub will update the PR for you.

2021-06-21 14:26 UTC, MGatner commented on public/assets/css/ci-theme.css
> +	width:100%;/*31%*/
No need to leave comments in place - `git` will track the whole history so cleaner just to remove things.
```suggestion
	width:100%;
```

2021-06-21 14:26 UTC, MGatner commented on public/assets/css/ci-theme.css
> +	/*margin-right:2%;*/
```suggestion
```

2021-06-21 14:26 UTC, MGatner commented on public/assets/css/ci-theme.css
> +		/*margin-left:10px;*/
```suggestion
		margin:30px;
```

2021-06-21 14:26 UTC, MGatner commented on public/assets/css/ci-theme.css
> +	width:70%;/*80%*/
```suggestion
	width:70%;
```

2021-06-21 14:26 UTC, MGatner commented on public/assets/css/ci-theme.css
> +	left:22%; /*10%*/
```suggestion
	left:22%;
```

2021-06-23 06:21 UTC, demyr17 commented
> 
> 
> Looks better! Thanks for this. No need to leave comments on the old versions of things as that will all be available in the revision history. I made suggestions to remove these - if you click the "Files" tab you can use the "Add suggestion to batch" buttons to add all of them to a new commit and GitHub will update the PR for you.

Is there anything I should do now? or was your warning for the future?

2021-06-23 12:06 UTC, MGatner commented
You need to update the PR. You can use the process I outlined above, or you can submit a new PR without the comments if that is easier. I recommend learning how to add commits from GitHub suggestions - it saves a lot of time for small changes.

2021-06-24 12:01 UTC, MGatner approved these changes
Thanks Demyr! Looks good.

2021-06-24 12:01 UTC, merged